global:
    scrape_interval: 5s
    evaluation_interval: 5s

rule_files:
    - ./alerts.yml

scrape_configs:
  - job_name: CajuBeneficiosApi
    metrics_path: /metrics
    scheme: http
    basic_auth:
        username: user
        password: pass
    static_configs:
        - targets:
            - host.docker.internal:8000
