kind: Deployment
apiVersion: apps/v1
metadata:
    name: caju-beneficios-api-deployment
    namespace: staging-apps
spec:
    replicas: 1
    selector:
        matchLabels:
            app: caju-beneficios-api
    template:
        metadata:
            labels:
                app: caju-beneficios-api
        spec:
            containers:
              - name: caju-beneficios-api
                image: docker.io/rempeloliveira/public:caju-beneficios-api.1.0.2-staging
                imagePullPolicy: Always
                ports:
                  - containerPort: 8000
                envFrom:
                  - secretRef:
                        name: caju-beneficios-api-secrets
                resources:
                    requests:
                        cpu: 250m
                        memory: 512Mi
                    limits:
                        cpu: 500m
                        memory: 1Gi
