kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
metadata:
    name: caju-beneficios-api-kustomization
    namespace: staging-apps
resources:
    - service.yml
    - deployment.yml
generators:
    - secrets.yml
generatorOptions:
    labels:
        deploy.type: kustomize
    disableNameSuffixHash: true
